name: build

on:
  push:
    branches:
      - main
  pull_request:


concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true
  
jobs:
  build:

    strategy:
      matrix:
        proj:
          - three-two-linear
          - three-two-treelike
          - two-one-central-versions

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0
        
    - name: Restore dependencies
      run: dotnet restore --locked-mode
      working-directory: ./${{ matrix.proj }}